added failed step

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -12,5 +12,9 @@ jobs:
   second job:
     runs-on: ubuntu-latest
     steps:
-      name: Say Goodbye
-      run: echo "Goodbye"
+      - name: Say Goodbye
+        run: echo "Goodbye"
+      - name: Failed Step
+        run: |
+          echo "This step will fail"
+          exit 1
